import type { Scene, StoryNode } from "@/lib/story/types";

export const STORY: Record<string, StoryNode> = {
  n1: {
    id: "n1",
    pose: "none",
    text: "The village used to have a color for every hour. Lately the hours arrive gray. Sound goes next. Then the smiles.",
    next: "n2",
  },
  n2: {
    id: "n2",
    who: "player",
    pose: "sit",
    text: "You are Blee. You barely speak. You are still smiling. You do not know why. That is becoming a problem.",
    next: "@village",
  },
  "look-lamp": {
    id: "look-lamp",
    text: "The lamp is on. It gives no light. Somebody still polishes it every morning.",
  },
  "look-house": {
    id: "look-house",
    text: "Through the window: a family at dinner. Nobody is talking. The forks are very loud.",
  },
  "look-sign": {
    id: "look-sign",
    text: "WELCOME. Someone scratched the smile off this sign. Someone else drew it back on. Badly. With love.",
  },
  "look-well": {
    id: "look-well",
    text: "A well full of dark. Far down, something small is laughing. It stops when you listen.",
  },
  n3: {
    id: "n3",
    who: "player",
    pose: "wait",
    text: "Behind the last shop a crack hangs in the air like a mouth that forgot how to close. It hums in a key nobody taught you.",
    next: "n4",
  },
  n4: {
    id: "n4",
    pose: "none",
    text: "You lean in. The village does not try to stop you. The crack does.",
    next: "n5",
  },
  n5: {
    id: "n5",
    pose: "none",
    text: "Falling takes longer than dying should. A voice finds you in the dark. It is not kind. It is not cruel. It is exact.",
    next: "n6",
  },
  n6: {
    id: "n6",
    pose: "none",
    speaker: "???",
    text: "Find why you are smiling.",
    next: "@under",
  },
  n7: {
    id: "n7",
    who: "nyang",
    speaker: "???",
    text: "mrrp. you landed on your face. impressive. the smile survived the drop. everything else did not.",
    next: "n8",
  },
  n8: {
    id: "n8",
    who: "nyang",
    speaker: "Nyang",
    text: "i am nyang. this hole is called blacksmile. smiles are born from feeling. something down here eats them. people up there forget how to laugh. you are late.",
    choices: [
      { label: "Where am I?", next: "n9a" },
      { label: "What eats them?", next: "n9b" },
      { label: "...", next: "n9c", set: "quiet" },
    ],
  },
  n9a: {
    id: "n9a",
    who: "nyang",
    speaker: "Nyang",
    text: "under the village. under the gray. smiles used to walk around like stray lights. now the lights go into a throat named null.",
    next: "n10",
  },
  n9b: {
    id: "n9b",
    who: "nyang",
    speaker: "Nyang",
    text: "null. it does not hate you. hate would be a feeling. it just subtracts. five smile cores still hold the world together. hunt those or the gray wins.",
    next: "n10",
  },
  n9c: {
    id: "n9c",
    who: "nyang",
    speaker: "Nyang",
    text: "silent type. fine. i talk enough for both of us. five cores. one eater. you, somehow, still grinning.",
    next: "n10",
  },
  n10: {
    id: "n10",
    who: "nyang",
    speaker: "Nyang",
    text: "i do not fight. i point. i judge. sometimes i hide a snack in your pocket and pretend i did not. go say hi to the robot and the loud flower. then the stair.",
  },
  "nyang-again": {
    id: "nyang-again",
    who: "nyang",
    speaker: "Nyang",
    text: "the stair is south. i am not your map. i am just usually right.",
  },
  "stair-blocked": {
    id: "stair-blocked",
    who: "nyang",
    speaker: "Nyang",
    text: "not yet. the robot and the loud flower want words with you. manners are also a map.",
  },
  n11: {
    id: "n11",
    who: "jenny",
    speaker: "Jenny",
    text: "SYSTEM BOOT. subject: blee. smile integrity: 97%. explanation: unknown. hello. i am jenny. i prefer numbers. numbers do not leave.",
    next: "n12",
  },
  n12: {
    id: "n12",
    who: "jenny",
    speaker: "Jenny",
    text: "this place will offer you buttons that look like harm. they are not. LOOK. WINK. WAIT. ASK. SPARE. if you strike first, you fail the first lesson on purpose.",
    next: "n13",
  },
  n13: {
    id: "n13",
    who: "jenny",
    speaker: "Jenny",
    text: "i am collecting data on why you smile. do not ask how much i already know. the answer is an integer i am not allowed to say.",
  },
  "jenny-again": {
    id: "jenny-again",
    who: "jenny",
    speaker: "Jenny",
    text: "smile integrity: still 97%. i will tell you when it changes. i will not tell you why.",
  },
  n14: {
    id: "n14",
    who: "flower",
    speaker: "Flower",
    text: "hi!! i am flower!! the village got quieter this morning!! i counted the missing laughs before anyone else did!!",
    next: "n15",
  },
  n15: {
    id: "n15",
    who: "flower",
    speaker: "Flower",
    text: "that is my job, i think!! being first to notice when a smile is gone!! please do not make me notice you!!",
    choices: [
      { label: "I will be careful.", next: "n16a", set: "gentle" },
      { label: "I am already smiling.", next: "n16b" },
    ],
  },
  n16a: {
    id: "n16a",
    who: "flower",
    speaker: "Flower",
    text: "good!! careful is a kind of smile too!! a small one!!",
    next: "n19",
  },
  n16b: {
    id: "n16b",
    who: "flower",
    speaker: "Flower",
    text: "i know!! that is why i am worried!! smiles that never turn off are the ones null can see from farthest away!!",
    next: "n19",
  },
  n19: {
    id: "n19",
    who: "flower",
    speaker: "Flower",
    text: "a slime is practicing being a monster on the stair!! it is bad at it!! please talk to it!! if you step on a friend the world gets grayer!!",
  },
  "flower-again": {
    id: "flower-again",
    who: "flower",
    speaker: "Flower",
    text: "still here!! still counting!! you are still smiling!! good!! scary!!",
  },
  n17: {
    id: "n17",
    who: "hider",
    speaker: "Hider",
    text: "...do not ask me the way. i know it. knowing is not the same as telling. i will remember what you do anyway.",
    next: "n18",
  },
  n18: {
    id: "n18",
    who: "hider",
    speaker: "Hider",
    text: "...the stair is south. i did not say that. you guessed.",
  },
  "hider-again": {
    id: "hider-again",
    who: "hider",
    speaker: "Hider",
    text: "...i said nothing. remember that.",
  },
  "stair-enter": {
    id: "stair-enter",
    text: "The stair keeps going down after the steps run out. The walls forgot their color on the way.",
  },
  n20: {
    id: "n20",
    who: "player",
    pose: "wait",
    text: "The stair has no color left. Something at the bottom wobbles like a feeling that has not chosen a shape.",
    next: "fight-1",
  },
  "fight-1": {
    id: "fight-1",
    who: "slime",
    speaker: "Slime",
    text: "blorp?",
    encounter: {
      name: "SMILE SLIME",
      who: "slime",
      spareAt: 3,
      acts: [
        {
          label: "LOOK",
          text: "A small Smile wearing a monster costume. The costume is losing. The smile is not.",
        },
        {
          label: "WINK",
          text: "You wink. The slime tries to wink back and becomes a happier circle by accident.",
          meter: 2,
          set: "winked",
        },
        {
          label: "WAIT",
          text: "You wait. It waits. Two things that cannot blink hold a truce.",
          meter: 1,
          set: "waited",
        },
        {
          label: "ASK",
          text: "You ask if it is lost. It leans on your shoe. That is a yes in gelatin.",
          meter: 1,
          set: "asked",
        },
        {
          label: "PET",
          text: "It is cold and sincere. For one second the gray recedes from the stair.",
          meter: 1,
          set: "kind",
        },
      ],
      spare: { label: "SPARE", next: "spare-1" },
      leave: { label: "WALK PAST", next: "flee-1" },
      hp: 30,
      defeat: { label: "", next: "slime-hurt", set: "hurt-slime" },
      defeatText: "The slime splits in two, then in four, then into a puddle that is still, somehow, smiling up at you.",
      flavor: "SMILE SLIME wobbles like it is trying to look scary.",
      attacks: [["bounce"], ["rain"], ["rise"], ["bounce", "rain"]],
      taunts: [
        "blorp! (that was a threat.)",
        "blorp blorp. (still a threat.)",
        "...blorp? (are you smiling at me?)",
        "blorp. (i forgot why i am fighting.)",
      ],
      damage: 3,
      seconds: 5,
    },
  },
  "spare-1": {
    id: "spare-1",
    who: "slime",
    speaker: "Slime",
    text: "blorp. (it will find you again. in shops. in alleys. in the places gray has not finished yet.)",
    next: "tv-kind",
  },
  "slime-hurt": {
    id: "slime-hurt",
    who: "slime",
    speaker: "Slime",
    text: "...blorp. (the puddle pulls itself back into a ball, very slowly, and does not look at you again.)",
    next: "tv-cold",
  },
  "flee-1": {
    id: "flee-1",
    who: "slime",
    speaker: "Slime",
    text: "blorp... (a smile tries to wave and is too small to finish it.)",
    next: "tv-cold",
  },
  "tv-kind": {
    id: "tv-kind",
    pose: "none",
    speaker: "TV Man",
    text: "BREAKING. local protagonist refuses to step on jelly. markets unchanged. hope up 0.4. we will return after these static flowers.",
    next: "spare-2",
  },
  "tv-cold": {
    id: "tv-cold",
    pose: "none",
    speaker: "TV Man",
    text: "BREAKING. local protagonist walks around a friend. temperature down. null licking its teeth on channel two. stay smiling.",
    next: "flee-2",
  },
  "spare-2": {
    id: "spare-2",
    who: "nyang",
    speaker: "Nyang",
    text: "see. a small smile can change your world. or at least the stair. i put a spare core-map in your pocket. do not thank me.",
    next: "null-1",
  },
  "flee-2": {
    id: "flee-2",
    who: "nyang",
    speaker: "Nyang",
    text: "you can keep walking past things. the gray likes that. it is efficient. i am not efficient. i am annoyed.",
    next: "null-1",
  },
  "null-1": {
    id: "null-1",
    pose: "none",
    text: "Far below the stair, something without a face drinks a lantern that used to be a laugh. It does not look up. It does not need to. It can hear a smile from here.",
    next: "null-2",
  },
  "null-2": {
    id: "null-2",
    pose: "none",
    speaker: "Null",
    text: ".....",
    next: "fight-null",
  },
  "fight-null": {
    id: "fight-null",
    who: "null",
    speaker: "Null",
    text: "It looks up. It has no face, and it is still somehow looking at yours.",
    encounter: {
      name: "NULL",
      who: "null",
      spareAt: 99,
      acts: [
        {
          label: "LOOK",
          text: "NULL. No color. No face. It eats the reason people smile and keeps the shape.",
        },
        {
          label: "SMILE",
          text: "You keep smiling. The edges of Null fizz like it tasted something sour.",
          set: "smiled-at-null",
        },
        {
          label: "CALL",
          text: "You call for Nyang. The stair swallows the name. Far above, something warm refuses to be swallowed.",
          set: "called-nyang",
        },
        {
          label: "HOLD",
          text: "You hold your ground. Your shoes are gray now. Your smile is not.",
        },
      ],
      spare: { label: "SPARE", next: "null-after" },
      flavor: "The gray is getting closer. Survive.",
      attacks: [["sweep"], ["ring"], ["close", "rain"]],
      taunts: ["why that face.", "gray is quiet. gray is kind.", "stop smiling."],
      damage: 4,
      seconds: 6,
      survive: { turns: 3, next: "null-after" },
    },
  },
  "null-after": {
    id: "null-after",
    who: "player",
    pose: "stand",
    text: "Null stops. Not because it lost. Because it learned your shape. It sinks back under the stair, and the floor under you sinks with it.",
    next: "@court",
  },
  "court-enter": {
    id: "court-enter",
    text: "You land in a hall cut cleanly in half. One side is white enough to hurt. The other is black enough to hide in. Two thrones. Two smiles. Both of them are looking at you.",
  },
  "look-seam": {
    id: "look-seam",
    text: "The seam down the middle of the hall is gray. Not dead gray. Waiting gray.",
  },
  "king-1": {
    id: "king-1",
    who: "white-king",
    speaker: "White King",
    text: "Halt. You walked in without a rule. Everything is beautiful only inside my rules.",
    next: "king-2",
  },
  "king-2": {
    id: "king-2",
    who: "white-king",
    speaker: "White King",
    text: "A smile with no reason is disorder. Disorder is corrected. Hold still. This is for your own tidiness.",
    next: "fight-king",
  },
  "fight-king": {
    id: "fight-king",
    who: "white-king",
    speaker: "White King",
    text: "The White King raises the Rule Scepter. The white half of the hall stands at attention.",
    encounter: {
      name: "WHITE KING",
      who: "white-king",
      boss: true,
      spareAt: 5,
      acts: [
        {
          label: "LOOK",
          text: "WHITE KING. Loves order, silence, clean things. Hates chaos, lies, and being interrupted. His scepter hums in straight lines.",
        },
        {
          label: "KNEEL",
          text: "You kneel. He nods, satisfied. It is the first time anyone has done what he asked without being made to.",
          meter: 1,
          set: "knelt",
        },
        {
          label: "TIDY",
          text: "You straighten a crooked tile with your shoe. The king's eye twitches. It might be gratitude.",
          meter: 1,
        },
        {
          label: "ASK WHY",
          text: "You ask why rules make things beautiful. He opens his mouth. Nothing comes out. That has never happened before.",
          meter: 2,
          set: "asked-king",
        },
        {
          label: "SMILE",
          text: "You smile without permission. He writes it down. His quill shakes a little.",
          meter: 1,
        },
      ],
      spare: { label: "SPARE", next: "king-spared", set: "beat-king" },
      hp: 90,
      defeat: { label: "", next: "king-fallen", set: "beat-king" },
      defeatText: "The Rule Scepter cracks down the middle. The White King goes down on one knee, which is not in any of his rules.",
      spareText: "You lower your hands. The White King lowers his scepter, exactly as far as you did. Not one inch more.",
      flavor: "The WHITE KING stands perfectly still. Even his cape is obeying.",
      attacks: [["pillars"], ["rows"], ["pillars", "sweep"], ["rows", "pillars"]],
      taunts: [
        "Everything has its order.",
        "That is what beauty is.",
        "You are only a variable.",
        "...why do you still smile?",
        "Stop. That is an order.",
      ],
      damage: 4,
      seconds: 6,
    },
  },
  "king-spared": {
    id: "king-spared",
    who: "white-king",
    speaker: "White King",
    text: "...Your smile has no reason. And yet it is tidy. Go. Before I write a rule against you. The queen is waiting. She is always waiting. It is very untidy.",
  },
  "king-fallen": {
    id: "king-fallen",
    who: "white-king",
    speaker: "White King",
    text: "...So this is disorder. It hurts in a very untidy way. Go on. The queen will enjoy you. That is not a compliment.",
  },
  "king-again": {
    id: "king-again",
    who: "white-king",
    speaker: "White King",
    text: "I am drafting a rule about you. Every draft comes out kind. I will keep trying.",
  },
  "queen-early": {
    id: "queen-early",
    who: "black-queen",
    speaker: "Black Queen",
    text: "Not yet, not yet. Go bother the boring one first. I want to see his face when you do.",
  },
  "queen-1": {
    id: "queen-1",
    who: "black-queen",
    speaker: "Black Queen",
    text: "Found something fun. You made the king blink. Nobody makes the king blink.",
    next: "queen-2",
  },
  "queen-2": {
    id: "queen-2",
    who: "black-queen",
    speaker: "Black Queen",
    text: "Isn't it fun? A little more chaos is fine, right? Let's break you a little and see what color comes out.",
    next: "fight-queen",
  },
  "fight-queen": {
    id: "fight-queen",
    who: "black-queen",
    speaker: "Black Queen",
    text: "The Black Queen draws the Chaos Blade. The black half of the hall starts laughing.",
    encounter: {
      name: "BLACK QUEEN",
      who: "black-queen",
      boss: true,
      spareAt: 5,
      acts: [
        {
          label: "LOOK",
          text: "BLACK QUEEN. Loves chaos, games, challenge, fun. Hates boredom, rules, and being taken seriously. Her blade never swings the same way twice.",
        },
        {
          label: "PLAY",
          text: "You play along. She laughs so hard the crown slips. She fixes it with the blade. Carefully.",
          meter: 2,
          set: "played-queen",
        },
        {
          label: "DANCE",
          text: "You dance badly. On purpose. She is offended by how much she likes it.",
          meter: 1,
        },
        {
          label: "BE BORING",
          text: "You stand very still and talk about taxes. She yawns. The next attack is faster, out of spite.",
        },
        {
          label: "SMILE",
          text: "You smile back at her. Hers wobbles, like it forgot it was a weapon.",
          meter: 1,
        },
      ],
      spare: { label: "SPARE", next: "queen-spared", set: "beat-queen" },
      hp: 90,
      defeat: { label: "", next: "queen-fallen", set: "beat-queen" },
      defeatText: "The Chaos Blade spins out of her hand and sticks in the ceiling. The Black Queen falls over laughing, and then just falls over.",
      spareText: "You offer your hand. The Black Queen takes it, spins you once, and lets go. Game over. She won. You won. Nobody knows.",
      flavor: "The BLACK QUEEN is humming a song that changes every bar.",
      attacks: [["spiral"], ["bounce", "ring"], ["spiral", "rain"], ["close", "spiral"]],
      taunts: [
        "Isn't this fun?",
        "The world should be full of fun, not rules!",
        "You might be my type of trouble.",
        "Don't get boring on me now.",
        "Again! Again!",
      ],
      damage: 4,
      seconds: 6,
    },
  },
  "queen-spared": {
    id: "queen-spared",
    who: "black-queen",
    speaker: "Black Queen",
    text: "Hah. You don't break. You bend and come back smiling. That's cheating. I love it.",
    next: "court-split",
  },
  "queen-fallen": {
    id: "queen-fallen",
    who: "black-queen",
    speaker: "Black Queen",
    text: "Ow. Okay. Ow. ...That was fun too. You hit like someone who has never been bored in their life.",
    next: "court-split",
  },
  "queen-again": {
    id: "queen-again",
    who: "black-queen",
    speaker: "Black Queen",
    text: "Again? Later. I'm saving you.",
  },
  "court-split": {
    id: "court-split",
    who: "player",
    pose: "stand",
    text: "The two thrones hum. For one second the white and the black touch at the seam and make a gray that is not dead. Same world. Different smile.",
    next: "end-1",
  },
  "end-1": {
    id: "end-1",
    who: "player",
    pose: "sit",
    ending: true,
    text: "Five Smile Cores still hold the color in. The White King and the Black Queen let you pass, but their cores stay locked in their crowns. Dark Flame. Skeleton. Joker. Still out there. Chapter one only gives you the reason to walk.",
    next: "gate-1",
  },
  "gate-1": {
    id: "gate-1",
    who: "jenny",
    shop: true,
    speaker: "Jenny",
    text: "CHAPTER 1 COMPLETE. cores remaining: 5. secret remaining: 1. i am not that secret. probably. the rest of the night costs one decision. just one. i checked.",
    choices: [
      { label: "Replay chapter one.", next: "n1" },
      { label: "Keep going (full game).", next: "shop-1" },
    ],
  },
  "shop-1": {
    id: "shop-1",
    who: "jenny",
    shop: true,
    paid: true,
    speaker: "Jenny",
    text: "the full game opens True Night and every chapter after it. one payment. no random boxes, no tricks. hider will not give you the map. he will watch you guess.",
    next: "c2-1",
  },
  "c2-1": {
    id: "c2-1",
    who: "player",
    pose: "stand",
    paid: true,
    text: "The second night smells like rain that never landed. A coat stands where a person should be.",
    next: "c2-2",
  },
  "c2-2": {
    id: "c2-2",
    paid: true,
    speaker: "Hider",
    text: "...you found the quiet road. most people take the loud one and call it a life. i remember the slime. i remember you.",
    next: "c2-3",
  },
  "c2-3": {
    id: "c2-3",
    who: "nyang",
    paid: true,
    speaker: "Nyang",
    text: "cores do not sit on a table labeled cores. they sit in people who forgot they were people. walk. i will complain the whole way.",
    next: "c2-end",
  },
  "c2-end": {
    id: "c2-end",
    who: "player",
    pose: "sit",
    paid: true,
    ending: true,
    text: "Chapter two stops on a rooftop that used to have a moon. The White King wants fewer choices. The Black Queen is collecting smiles. Your own smile stays on. You still do not know why.",
    choices: [{ label: "Return to chapter one.", next: "n1" }],
  },
};

const SCENES: Record<string, Scene> = {
  n1: "wake",
  n2: "wake",
  n3: "wake",
  n4: "wake",
  n5: "wake",
  n6: "wake",
  n7: "alley",
  n8: "alley",
  n9a: "alley",
  n9b: "alley",
  n9c: "alley",
  n10: "alley",
  n11: "alley",
  n12: "alley",
  n13: "alley",
  n14: "alley",
  n15: "alley",
  n16a: "alley",
  n16b: "alley",
  n17: "alley",
  n18: "alley",
  n19: "stair",
  n20: "stair",
  "fight-1": "stair",
  "spare-1": "after",
  "flee-1": "after",
  "tv-kind": "after",
  "tv-cold": "after",
  "spare-2": "after",
  "flee-2": "after",
  "null-1": "after",
  "null-2": "after",
  "fight-null": "after",
  "null-after": "after",
  "king-1": "after",
  "king-2": "after",
  "fight-king": "after",
  "queen-1": "after",
  "queen-2": "after",
  "fight-queen": "after",
  "queen-spared": "after",
  "queen-fallen": "after",
  "king-fallen": "after",
  "slime-hurt": "after",
  "court-split": "after",
  "end-1": "after",
  "gate-1": "after",
  "shop-1": "after",
  "c2-1": "after",
  "c2-2": "after",
  "c2-3": "after",
  "c2-end": "after",
};

export function getNode(id: string): StoryNode {
  const node = STORY[id] ?? STORY.n1;
  return { ...node, scene: node.scene ?? SCENES[node.id] ?? "wake" };
}
