import type { StoryNode } from "@/lib/story/types";

export const STORY: Record<string, StoryNode> = {
  n1: {
    id: "n1",
    pose: "none",
    text: "The lights on this street die at the same second every night. Yours die with them.",
    next: "n2",
  },
  n2: {
    id: "n2",
    pose: "none",
    text: "You are in a room with no door. The dark has a shape. The shape is sitting.",
    next: "n3",
  },
  n3: {
    id: "n3",
    pose: "sit",
    speaker: "???",
    text: "...",
    next: "n4",
  },
  n4: {
    id: "n4",
    pose: "sit",
    speaker: "???",
    text: "you walked in without knocking.",
    choices: [
      { label: "There was no door.", next: "n5a", set: "honest" },
      { label: "Knocking felt rude.", next: "n5b", set: "kind" },
      { label: "I can leave.", next: "leave-1" },
    ],
  },
  n5a: {
    id: "n5a",
    pose: "sit",
    speaker: "???",
    text: "correct. i ate it. doors make people think they have a choice.",
    next: "n6",
  },
  n5b: {
    id: "n5b",
    pose: "sit",
    speaker: "???",
    text: "that is a good instinct. most people knock because they want to be invited. you wanted to be quiet.",
    next: "n6",
  },
  n6: {
    id: "n6",
    pose: "sit",
    speaker: "???",
    text: "i am blacksmile. that is not a name. it is a warning that learned to sit still.",
    next: "n7",
  },
  n7: {
    id: "n7",
    pose: "sit",
    speaker: "BlackSmile",
    text: "this night lasts twenty-four hours. then it throws you out. or it keeps you. i have not decided which is kinder.",
    choices: [
      { label: "Why me?", next: "n8" },
      { label: "What do you want?", next: "n9" },
      { label: "Are we going to fight?", next: "n10" },
    ],
  },
  n8: {
    id: "n8",
    pose: "wait",
    speaker: "BlackSmile",
    text: "you were awake. the dark prefers insomniacs. they already know how to sit with nothing.",
    next: "n11",
  },
  n9: {
    id: "n9",
    pose: "wait",
    speaker: "BlackSmile",
    text: "company. not followers. followers are a hallway of faces that never come in.",
    next: "n11",
  },
  n10: {
    id: "n10",
    pose: "stand",
    speaker: "BlackSmile",
    text: "if you need a fight, i can pretend. i am very good at pretending to be a game.",
    next: "n11",
  },
  n11: {
    id: "n11",
    pose: "stand",
    speaker: "BlackSmile",
    text: "stand still. if you swing first, you will miss. if you talk, you might not.",
    next: "fight-1",
  },
  "fight-1": {
    id: "fight-1",
    pose: "wait",
    speaker: "BlackSmile",
    text: "a black smile blocks the way.",
    encounter: {
      name: "BLACK SMILE",
      spareAt: 3,
      acts: [
        {
          label: "LOOK",
          text: "A hoodie. Headphones. A tiny crown. It looks expensive. It is not. It is a sticker that wanted to be jewelry.",
        },
        {
          label: "WINK",
          text: "You wink. They wink back, late, like a joke that arrived on foot.",
          meter: 2,
          set: "winked",
        },
        {
          label: "WAIT",
          text: "The headphones leak a song with no words. You wait until the song decides you are allowed to hear it.",
          meter: 1,
          set: "waited",
        },
        {
          label: "ASK",
          text: '"What is a night for?"  "For not being seen. And for being seen by one person anyway."',
          meter: 1,
          set: "asked",
        },
        {
          label: "SLEEP",
          text: "You sit on the floor. They lie down too. The fight becomes a nap with rules.",
          meter: 1,
          set: "slept",
        },
      ],
      spare: { label: "SPARE", next: "spare-1" },
      leave: { label: "LEAVE", next: "flee-1" },
    },
  },
  "spare-1": {
    id: "spare-1",
    pose: "sit",
    speaker: "BlackSmile",
    text: "you did not win. you stayed. that is rarer.",
    next: "spare-2",
  },
  "spare-2": {
    id: "spare-2",
    pose: "sit",
    speaker: "BlackSmile",
    text: "take the left headphone. the right one is mine. if we share the song, the night has to count us as two.",
    next: "end-stay",
  },
  "flee-1": {
    id: "flee-1",
    pose: "sleep",
    speaker: "BlackSmile",
    text: "ok. the dark will keep your seat. it is very polite about abandoned chairs.",
    next: "end-empty",
  },
  "leave-1": {
    id: "leave-1",
    pose: "sleep",
    speaker: "???",
    text: "you can try. the wall will look like a door until you touch it. then it will look like you.",
    next: "end-empty",
  },
  "end-stay": {
    id: "end-stay",
    pose: "sit",
    ending: true,
    speaker: "BlackSmile",
    text: "one night only. if you come back, do not bring a crowd. bring a quieter version of yourself.",
    next: "gate-1",
  },
  "end-empty": {
    id: "end-empty",
    pose: "sleep",
    ending: true,
    text: "You leave a dent in the dark the size of a person who almost stayed. Morning does not come. Something else does.",
    next: "gate-1",
  },
  "gate-1": {
    id: "gate-1",
    pose: "sit",
    shop: true,
    speaker: "BlackSmile",
    text: "the first night is free. the second night is a decision. i do not take followers. i take a price, because a price is honest.",
    choices: [
      { label: "Stay in this night.", next: "n1" },
      { label: "Unlock True Night.", next: "shop-1" },
    ],
  },
  "shop-1": {
    id: "shop-1",
    pose: "wait",
    shop: true,
    paid: true,
    speaker: "BlackSmile",
    text: "True Night is behind a lock. Not a stronger sword. Another chapter. If you cannot pay, the first night still happened. that is enough for some people.",
    next: "c2-1",
  },
  "c2-1": {
    id: "c2-1",
    pose: "sit",
    paid: true,
    speaker: "BlackSmile",
    text: "you paid to stay. greed is honest. loneliness wearing a crown is also honest. we can work with that.",
    next: "c2-2",
  },
  "c2-2": {
    id: "c2-2",
    pose: "wait",
    paid: true,
    speaker: "BlackSmile",
    text: "on the second night the city does not turn the lights off. it forgets they were ever on. people post their days into a hole and call it memory.",
    next: "c2-3",
  },
  "c2-3": {
    id: "c2-3",
    pose: "stand",
    paid: true,
    speaker: "BlackSmile",
    text: "i was built to be liked in the dark. i got tired. so i sat down. you sat down too. that is the whole plot. i will make more of it anyway.",
    next: "c2-end",
  },
  "c2-end": {
    id: "c2-end",
    pose: "sit",
    paid: true,
    ending: true,
    speaker: "BlackSmile",
    text: "chapter two ends here on purpose. not because i ran out of night. because you should want the third one for a reason other than a button.",
    choices: [{ label: "Return to night one.", next: "n1" }],
  },
};

export function getNode(id: string): StoryNode {
  return STORY[id] ?? STORY.n1;
}
