import type { Scene, StoryNode } from "@/lib/story/types";

export const STORY: Record<string, StoryNode> = {
  n1: {
    id: "n1",
    pose: "none",
    text: "You wake up already smiling. That is the first strange thing. The second is the crown on your headphone. It is a sticker. It is doing its best.",
    next: "n2",
  },
  n2: {
    id: "n2",
    who: "player",
    pose: "sit",
    text: "Hoodie. Headphones. A night that forgot to end. You are BlackSmile. You do not remember applying for the job.",
    next: "n3",
  },
  n3: {
    id: "n3",
    who: "nyang",
    speaker: "???",
    text: "mrrp. you are late. the dark already started without you.",
    next: "n4",
  },
  n4: {
    id: "n4",
    who: "nyang",
    speaker: "Nyang",
    text: "i am nyang. i give hints, and also judgment. mostly judgment.",
    choices: [
      { label: "Where am I?", next: "n5a" },
      { label: "Did I die?", next: "n5b" },
      { label: "You are a cat.", next: "n5c" },
    ],
  },
  n5a: {
    id: "n5a",
    who: "nyang",
    speaker: "Nyang",
    text: "the in-between. lights go out, people post their days into a hole, and something keeps the leftovers. tonight the leftover is you.",
    next: "n6",
  },
  n5b: {
    id: "n5b",
    who: "nyang",
    speaker: "Nyang",
    text: "if you died, you would not still be trying to look cool. you are lost. lost is cheaper than dead.",
    next: "n6",
  },
  n5c: {
    id: "n5c",
    who: "nyang",
    speaker: "Nyang",
    text: "observant. we will get along, or we will not. either way i will sit on your save file.",
    next: "n6",
  },
  n6: {
    id: "n6",
    who: "nyang",
    speaker: "Nyang",
    text: "don't worry. we'll end up smiling anyway. that is not comfort. that is a spoiler.",
    next: "n7",
  },
  n7: {
    id: "n7",
    who: "jenny",
    speaker: "Jenny",
    text: "SYSTEM BOOT. hello, protagonist. i am jenny. i am older than this night and worse at lying.",
    next: "n8",
  },
  n8: {
    id: "n8",
    who: "jenny",
    speaker: "Jenny",
    text: "this world has buttons that look like violence. they are not. LOOK. WINK. WAIT. ASK. SPARE. if you swing first, you fail the tutorial on purpose.",
    next: "n9",
  },
  n9: {
    id: "n9",
    who: "flower",
    speaker: "Flower",
    text: "hi!! i am flower!! i believe in you so loudly it might count as an attack!!",
    next: "n10",
  },
  n10: {
    id: "n10",
    who: "flower",
    speaker: "Flower",
    text: "a slime is blocking the stair. it is cute. it is also sticky. please do not step on a friend.",
    next: "n11",
  },
  n11: {
    id: "n11",
    who: "player",
    pose: "wait",
    text: "The stair has no railing. Something at the bottom wobbles like a thought that wants a hug.",
    next: "fight-1",
  },
  "fight-1": {
    id: "fight-1",
    who: "slime",
    speaker: "Slime",
    text: "blorp?",
    encounter: {
      name: "SLIME",
      who: "slime",
      spareAt: 3,
      acts: [
        {
          label: "LOOK",
          text: "A white blob with two serious eyes. It is practicing being a monster. It is not convincing.",
        },
        {
          label: "WINK",
          text: "You wink. The slime wobbles into a smile, then pretends that was an accident.",
          meter: 2,
          set: "winked",
        },
        {
          label: "WAIT",
          text: "You wait. The slime waits. This is a staring contest between two things that cannot blink.",
          meter: 1,
          set: "waited",
        },
        {
          label: "ASK",
          text: '"Are you lost too?" The slime leans on your shoe. That is a yes in gelatin.',
          meter: 1,
          set: "asked",
        },
        {
          label: "PET",
          text: "It is cold and sincere. For one second you both forget the plot.",
          meter: 1,
          set: "kind",
        },
      ],
      spare: { label: "SPARE", next: "spare-1" },
      leave: { label: "LEAVE", next: "flee-1" },
    },
  },
  "spare-1": {
    id: "spare-1",
    who: "slime",
    speaker: "Slime",
    text: "blorp. (translation: you may pass. also, please do not tell the joker i was nice.)",
    next: "spare-2",
  },
  "spare-2": {
    id: "spare-2",
    who: "nyang",
    speaker: "Nyang",
    text: "see. a small smile can change your world. or at least the stair. i will take the stair.",
    next: "end-stay",
  },
  "flee-1": {
    id: "flee-1",
    who: "slime",
    speaker: "Slime",
    text: "blorp... (it sounds like a door closing on a very small person.)",
    next: "end-empty",
  },
  "end-stay": {
    id: "end-stay",
    who: "player",
    pose: "sit",
    ending: true,
    text: "The first night lets you keep the slime's wobble in your pocket. Somewhere above the city, a king of light and a queen of dark are already arguing about you.",
    next: "gate-1",
  },
  "end-empty": {
    id: "end-empty",
    who: "player",
    pose: "sleep",
    ending: true,
    text: "You walk around the stair. The night notices. It does not shout. It just gets a little colder.",
    next: "gate-1",
  },
  "gate-1": {
    id: "gate-1",
    who: "jenny",
    shop: true,
    speaker: "Jenny",
    text: "CHAPTER 1 COMPLETE. the second night costs a decision. white king. black queen. tv man. i would not start with tv man.",
    choices: [
      { label: "Replay night one.", next: "n1" },
      { label: "Unlock True Night.", next: "shop-1" },
    ],
  },
  "shop-1": {
    id: "shop-1",
    who: "jenny",
    shop: true,
    paid: true,
    speaker: "Jenny",
    text: "True Night is not a stronger wink. it is chapter two. hider is waiting in a coat that is also a shadow. he hates being on time.",
    next: "c2-1",
  },
  "c2-1": {
    id: "c2-1",
    who: "player",
    pose: "stand",
    paid: true,
    text: "The second night smells like rain that never landed. A coat stands where a person should be.",
    next: "c2-2",
  },
  "c2-2": {
    id: "c2-2",
    paid: true,
    speaker: "Hider",
    text: "...you found the quiet road. most people take the loud one and call it a feed.",
    next: "c2-3",
  },
  "c2-3": {
    id: "c2-3",
    who: "nyang",
    paid: true,
    speaker: "Nyang",
    text: "the girl in the deep hood is watching. the ghost is watching the girl. the merchant will sell you something you already have. this is what a world looks like.",
    next: "c2-end",
  },
  "c2-end": {
    id: "c2-end",
    who: "player",
    pose: "sit",
    paid: true,
    ending: true,
    text: "Chapter two stops on a rooftop. The White King lights a window. The Black Queen closes it. Your smile stays on. That was always the point.",
    choices: [{ label: "Return to night one.", next: "n1" }],
  },
};

const SCENES: Record<string, Scene> = {
  n1: "wake",
  n2: "wake",
  n3: "alley",
  n4: "alley",
  n5a: "alley",
  n5b: "alley",
  n5c: "alley",
  n6: "alley",
  n7: "alley",
  n8: "alley",
  n9: "stair",
  n10: "stair",
  n11: "stair",
  "fight-1": "stair",
  "spare-1": "after",
  "spare-2": "after",
  "flee-1": "after",
  "end-stay": "after",
  "end-empty": "after",
  "gate-1": "after",
  "shop-1": "after",
  "c2-1": "after",
  "c2-2": "after",
  "c2-3": "after",
  "c2-end": "after",
};

export function getNode(id: string): StoryNode {
  const node = STORY[id] ?? STORY.n1;
  return { ...node, scene: node.scene ?? SCENES[node.id] ?? "wake" };
}
